ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'products.views.home', name='home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^cart/$', 'carts.views.view', name='cart'),
    url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$', 'carts.views.add_to_cart', name='add_to_cart'),
    url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single_product'),
    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)	 	
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(null=True, blank=True)
	price = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
	sale_price = models.DecimalField(decimal_places=2, max_digits=100, null=True, blank=True)
	slug = models.SlugField(unique=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False) #auto_now=False, Change when update
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)
	update_defaults = models.BooleanField(default=False)

	def __unicode__(self):
		return self.title

	def get_price(self):
		return self.price

	class Meta:
		unique_together = ('title', 'slug')

	def get_absolute_url(self):
		return reverse("single_product", kwargs={"slug": self.slug})

class ProductImage(models.Model):
	product = models.ForeignKey(Product)
	image = models.ImageField(upload_to='products/images/')
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=False)
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self):
		return self.product.title

class VariationManager(models.Manager):
	def all(self):
		return super(VariationManager, self).filter(active=True)

	def sizes(self):
		return self.all().filter(category='size')

	def colors(self):
		return self.all().filter(category='color')


VAR_CATEGORIES = (
	('size', 'size'),
	('color', 'color'),
	('package', 'package'),
	)


class Variation(models.Model):
	product = models.ForeignKey(Product)
	category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size')
	title = models.CharField(max_length=120)
	image = models.ForeignKey(ProductImage, null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	objects = VariationManager()

	def __unicode__(self):
		return self.title

products/views.py
from django.shortcuts import render, Http404
from .models import Product, ProductImage
from django.conf import settings
from marketing.models import MarketingMessage

# Create your views here.
def home(request): # When I enter a URL, I'm making a request. This request is being handled at home.
	# print "Inside home():"
	# print request
	# print "_________________________________________" 
	print request.POST
	products = Product.objects.all()
	marketing_message=MarketingMessage.objects.all()[0]
	context = {'products': products, 'marketing_message': marketing_message}
	template='products/home.html'
	return render(request, template, context)


def all(request):
	products = Product.objects.all()
	context = {'products': products}
	template = 'products/all.html'	
	return render(request, template, context)

def single(request, slug):
	try:
		product = Product.objects.get(slug=slug)
		images = ProductImage.objects.filter(product=product)
		context = {'product': product, "images": images}
		template = 'products/single.html'	
		return render(request, template, context)
	except:
		return Http404
	

def search(request):
	try:
		q = request.GET.get('q')
	except:
		q = None
	
	if q:
		products = Product.objects.filter(title__icontains=q)
		context = {'query': q, 'products': products}
		template = 'products/results.html'	
	else:
		template = 'products/home.html'	
		context = {}
	return render(request, template, context)

templates/products/all.html
{% extends 'base.html' %}


{% load staticfiles %}

{% block head_title %}
Products || 
{% endblock %}

{% block styles %}
.jumbotron {
	/*color: red;*/
}
{% endblock %}


{# Comments here #}


{% block content %}




<div class='row'>

{% for product in products %}
		<div class='col-sm-2'>



			<div class="thumbnail">
					{% if product.productimage_set.all %}

							{% for item in product.productimage_set.all %}

							{% if item.featured %}
							<div style="width:100px;margin:0 auto;">

								<a href='{{ product.get_absolute_url }}'>
									<div class='background_img_thumb' style="height:100px;background-image: url('{{ MEDIA_URL }}{{ item.image }}');"></div>
								</a>
							</div>
							<!-- <img class='img-responsive' src="{{ MEDIA_URL }}{{ item.image }}" /> -->
							{% endif %}
							 


							{% endfor %}

					{% else %}
					<div style="width:100px;margin:0 auto;">

								<a href='{{ product.get_absolute_url }}'>
									<div class='background_img_thumb' style="height:100px;"></div>
								</a>
							</div>
					{% endif %}

					<div class="caption">
					<a href='{{ product.get_absolute_url }}'> <h3>{{ product.title }}</h3></a>
					<p>{{ product.description|truncatewords:15}}</p>
					<p><a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">View</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
					</div>
		   	 </div>


		</div>

{% cycle "" "" "" "" "" "</div><br/><hr/><div class='row'>" %}
{% endfor %}

</div>

{% endblock %}

templates/products/home.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- {% block head_title %} CFE Home {% endblock %}  -->

{% block jumbotron2 %}
<div class="container">
<div class="jumbotron ">
        <h1>Hi User</h1>
        <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>To see the difference between static and fixed top navbars, just scroll.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
        </p>
</div>
</div>


{% endblock %}


{% block content %}


<div class="row ">
{% for product in products %}
	<div class="col-sm-4">
		<div class="thumbnail">
		{% if product.productimage_set.all %}
							{% for item in product.productimage_set.all %}							
								{% if item.featured %}    
					      			<img src="{{ MEDIA_URL }}{{item.image}}" style="height:250px; width: 300px;" alt="{{product.title}}">					      			
								{% endif %}
							{% endfor %}

				      <div class="caption">
				        <h3>{{product.title}}</h3>
				        <p>{{product.description| truncatewords:15}}</p>
				        <p><a href="{% url 'single_product' product.slug  %}" class="btn btn-primary" role="button" >View</a> </p>
				      </div>
		{% else %}
		<img src='{% static "img/Placeholder.png" %}' style="height:250px; width: 300px;" class="img-responsive" >
		<div class="caption">
				        <h3>{{product.title}}</h3>
				        <p>{{product.description| truncatewords:15}}</p>
				        <p><a href="{% url 'single_product' product.slug  %}" class="btn btn-primary" role="button" >View</a> </p>
				      </div>
		{% endif %}
		</div>
  </div>


{% cycle "" "" "</div><div class='row'>" %}

{% endfor %}
{% endblock %}

</div>

templates/products/results.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<h1>Searched for '{{query}}'</h1>
<table class='table'>
<thead>
<th></th>
<th>Product</th>
</thead>

<tbody>
{% for product in products %}
	<tr>
	<td style="width:160px; height:160px;">

	{% if product.productimage_set.all %}
		{% for item in product.productimage_set.all %}
			{% if item.featured %}

 	<a href='{{ product.get_absolute_url }}'>
 		<div class='background_img_thumb' style="height:160px;background-image: url('{{ MEDIA_URL }}{{ item.image }}');background-size:cover;"></div>
 	</a>

			{% endif %}
		{% endfor %}

	{% else %}
	<a href='{{ product.get_absolute_url }}'>
	<div class='background_img_thumb' style="height:160px; background-image:url('{% static "img/Placeholder.png" %}');background-size:cover;background-position:center; " ></div>
	</a>



	{% endif %}
	</td>
	<td>
	<a href='{{ product.get_absolute_url }}'>
	{{ product }}</a>
	</td>
	</tr>
{% endfor %}

</tbody>


</table>

{% endblock %}

templates/products/single.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
  <h1>{{product.title}} <small>${{product.price}}</small></h1>
  <form class='form' method='POST' action='{% url "add_to_cart" product.slug %}'> {% csrf_token %}
	<input name="qty" type="number" value='1' class="form-group">
	<!-- <input name="attr" type="text" placeholder='color' class="form-group"> -->
	{%if product.variation_set.all%}
			<select class="form-control" name='size'>
			{%if product.variation_set.sizes%}
				{% for item in product.variation_set.sizes %}				
				<option value="{{ item.title|lower }}"> {{ item.title|capfirst }}</option>		
				{% endfor %}
			</select>
			{% endif %}
			{%if product.variation_set.colors%}
				<select class="form-control" name='color'>
					{% for item in product.variation_set.colors %}
					<option value="{{ item.title|lower }}"> {{ item.title|capfirst }}</option>		
					{% endfor %}
				</select>
			{% endif %}			
	</select>
	{% endif %}
	<input type="submit" value="Add to Cart" class="btn btn-default">	
</form>
</div>


<div class="row">
<div class="col-sm-4">
{% for img in images %}

	{% if img.featured %}
		<h2> Featured </h2>
		<img src="{{ MEDIA_URL }}{{img.image}}" class="img-responsive" style="height:350px; width: 500px;">
	{% endif %}
	{% if not img.featured %}
		<img src="http://placehold.it/350x150" class="img-responsive">
	{% endif %}
	

{% endfor %}
</div>
<div class="col-sm-8">
	{{product.description| linebreaks}}
	</div>
</div>
{% endblock %}